import { MASK_ORDER_EPSILON } from "../canvas-media/mask-order.ts";
import { OBJECT_SDF_MARGIN, OBJECT_SDF_TILE } from "../canvas-media/object-shape.ts";
import {
  MASK_BACKING_GREY_LEVEL,
  MASK_BUMP_STRENGTH,
  MASK_HIGHLIGHT_STROKE_WIDTH_PX,
  MASK_LIGHT_HEIGHT_SCALE,
  MASK_OBJECT_SWELL,
  MASK_OBJECT_SWELL_LIMIT,
  MASK_SHADOW_NEAR,
  MASK_SHADOW_STEPS,
  MASK_STROKE_COLOR,
  MASK_STROKE_WIDTH_PX,
  MAX_MASK_LIGHT_SOURCES,
  MAX_MASK_OBJECTS,
  LIGHT_SDF_ATLAS,
  LIGHT_SDF_GRID,
  OBJECT_GRADIENT_LIMIT,
  OBJECT_SDF_ATLAS,
  OBJECT_SDF_GRID,
  OBJECT_SDF_RANGE,
} from "../mask-constants.ts";

function glFloat(n: number): string {
  return n.toFixed(6);
}

const SHADER_CONSTANTS: Record<string, number | string> = {
  MAX_MASK_OBJECTS,
  MASK_OBJECT_SWELL: glFloat(MASK_OBJECT_SWELL),
  MASK_OBJECT_SWELL_LIMIT: glFloat(MASK_OBJECT_SWELL_LIMIT),
  OBJECT_SDF_TILE: glFloat(OBJECT_SDF_TILE),
  OBJECT_SDF_GRID: glFloat(OBJECT_SDF_GRID),
  OBJECT_SDF_ATLAS: glFloat(OBJECT_SDF_ATLAS),
  OBJECT_SDF_MARGIN: glFloat(OBJECT_SDF_MARGIN),
  OBJECT_SDF_RANGE: glFloat(OBJECT_SDF_RANGE),
  OBJECT_GRADIENT_LIMIT: glFloat(OBJECT_GRADIENT_LIMIT),
  OBJECT_ORDER_EPSILON: glFloat(MASK_ORDER_EPSILON),
  MAX_LIGHT_SOURCES: MAX_MASK_LIGHT_SOURCES,
  LIGHT_SDF_GRID: glFloat(LIGHT_SDF_GRID),
  LIGHT_SDF_ATLAS: glFloat(LIGHT_SDF_ATLAS),
  MASK_SHADOW_STEPS,
  MASK_SHADOW_NEAR: glFloat(MASK_SHADOW_NEAR),
  BUMP_STRENGTH: glFloat(MASK_BUMP_STRENGTH),
  LIGHT_HEIGHT_SCALE: glFloat(MASK_LIGHT_HEIGHT_SCALE),
  STROKE_WIDTH_PX: glFloat(MASK_STROKE_WIDTH_PX),
  HIGHLIGHT_STROKE_WIDTH_PX: glFloat(MASK_HIGHLIGHT_STROKE_WIDTH_PX),
  BACKING_GREY_LEVEL: glFloat(MASK_BACKING_GREY_LEVEL),
  STROKE_COLOR: `vec3(${MASK_STROKE_COLOR.slice(0, 3).map(glFloat).join(", ")})`,
  STROKE_ALPHA: glFloat(MASK_STROKE_COLOR[3]),
};

export const CONSTANTS_GLSL = Object.entries(SHADER_CONSTANTS)
  .map(([name, value]) => `#define ${name} ${value}`)
  .join("\n");
